### ISSUE TITLE
Regression: Log default values

### ISSUE THREAD

**Issue by bastianilso** [med-material/VREyeTrackingAccuracyTest#12]
See my comment in pull request #10 : 

> Instead of commenting out the code, I would like you to make the code use what corresponds to our default values. So, if ShowGazeDot by default is true, replace private Toggle showGazeDot; with private bool showGazeDot = true; and fix the code references accordingly. We still intend LoggingManager to log these values.

**Comment by YoNeXia** [comment]
This issue was resolved in pull request #14 . 🐭
