### ISSUE TITLE
MainMenu UI: Connect the Dropdown to the actual code

### ISSUE THREAD

**Issue by bastianilso** [med-material/VREyeTrackingAccuracyTest#13]
When we implement and revamp the main menu, we should retain the functionality which the old main menu provided. Therefore the code needs to be updated to work using the new main menu dropdown design.

**Comment by YoNeXia** [comment]
To connect the Dropdown from the new UI, I am going to check the old version of the program. I run it in Unity with the old UI and check how its work.
When I find it, I am going to implement new code for using the new dropdown.

**Comment by YoNeXia** [comment]
I implement the dropdown inside the code.
Before, the code use just a `if else` to set up the time for switch circles.
I replace it by a `switch`, but this one does not work... I am trying to understand why.

![Code](https://user-images.githubusercontent.com/23256059/67861516-a65abb00-fb20-11e9-94ab-58b383fa6899.png)

`targetLifeSpan` is a `public static float`

**Comment by YoNeXia** [comment]
I set a fixed value into the old and the new program...
![Fixed value](https://user-images.githubusercontent.com/23256059/67935837-f5f5c100-fbca-11e9-9f0e-47eef0850855.png)
The old program work but not the new, so I am trying to find a solution, but I am blocked for the moment.

**Comment by bastianilso** [comment]
@YoNeXia how does targetLifeSpan work? Where is it used?

**Comment by bastianilso** [comment]
@YoNeXia what can we do to narrow down the possible sources for this issue? What have you tried so far?

**Comment by YoNeXia** [comment]
@bastianilso The `targetLifeSpan` variable is a float. In old program, it takes the value of the apparence time of circles in the test. It used in StartConfig.cs, and some operation are made in CircleLife.cs.
And I connect the dropdown with `switch case` as you can see upper.
As my switch case does not work, I fix the value, and as I said before he does not work in new program.
I am trying to find a solution now, but no idea for the moment... And I do not have any idea where is the source of this issue, I would to find it.

**Comment by YoNeXia** [comment]
@bastianilso Ok I found it. Its because we fix default values at old toggles. And the old toggle inputMode in StartConfig.cs control the mode of the circles, automatic with timer or manual with spacebar. 😅
I am going to resolve it now. 👍

**Comment by bastianilso** [comment]
@YoNeXia Your Pull Request #16 has been merged, so I am closing this issue.
