### ISSUE TITLE
Data log into CSV files

### ISSUE THREAD

**Issue by YoNeXia** [med-material/VREyeTrackingAccuracyTest#18]
Data are logged into a CSV file, at the path `C:\Users\username\Documents\_GazeData`, but this data is only default values.
![GazeData](https://user-images.githubusercontent.com/23256059/68013504-649b5300-fc8d-11e9-9e3e-4d48c95994b3.png)

This default values `No test scene`, `None` and `NaN` are not the true values. So need to log true values into CSV files.
To know what values need to log, just check README file, or the screen upper.

**Comment by bastianilso** [comment]
Have a column called event:
- Configuration is running
- Calibration is running
- Accuracy Tests is counting down
- Accuracy Test is running.
- Accuracy Test ended

**Comment by YoNeXia** [comment]
I try the program with the VR headset connected and I show different results…

Next screens are from a CSV file, created during the test in `C:\Users\username\Documents\_GazeData`

So I have this when I am not in Circle Test Scene:
![image](https://user-images.githubusercontent.com/23256059/69610845-e97b5180-102c-11ea-95f0-1fc39ad9ba8d.png)

This when Circle Test Scene load :
![image](https://user-images.githubusercontent.com/23256059/69610863-f5671380-102c-11ea-9168-a05cf6e9ecfe.png)

And this during the test :
![image](https://user-images.githubusercontent.com/23256059/69610906-0748b680-102d-11ea-8faf-d8af7d5162a5.png)

**Comment by YoNeXia** [comment]
Actually, log begin when the calibration begin. So, when the facilitator configure parameters in MainScene, nothing is logged.
The event "Configuration is running" can not be print in CSV file with the actual logger.

This is why the script managing the data logger is currently lunching during the calibration and work only when 2D Calibration Demo scene is running. If we change the scene, logger is stopped.

When the program is running, we can not detect the switch between the calibration and the accuracy test, because CircleTest scene is control by Pupil plugin script into 2D Calibration Demo. So the program never have switch between 2D Calibration Demo and CircleTest scene. We stay in 2D Calibration Demo after the configuration is made.
This can be observated with the top of your Unity window when the program is running, because the name of the scene running is printed. And in our case, it never change between calibration and accuracy test.

So, I am actually trying detect the different events in the actual logger by other actions of switch scene.

**Comment by YoNeXia** [comment]
Hey @bastianilso.
I can log what I want, sometimes I have a little problem...
When the accuracy test is running, sometimes I have the event "Accuracy Test ended". This event appear during circle switch.

![CSV Event Bug](https://user-images.githubusercontent.com/23256059/70425711-f6a73000-1a71-11ea-90d2-78d2f874df5d.png)

I know why the name of the circle is logged, because in the code we check if the circle index exist or not, when for other data, we check if circle exist.
![image](https://user-images.githubusercontent.com/23256059/70426154-d3c94b80-1a72-11ea-9a78-641c2e2a7487.png)
![image](https://user-images.githubusercontent.com/23256059/70426178-de83e080-1a72-11ea-9d4b-9def241b0cec.png)

The circle does not exist so we have `NaN` values for the position and `Accurracy Test Ended` event.

I propose:
- if the circle exist, get the name of current circle, `circleObject != null`.
- if the circle exist, get the positions of current circle, `circleObject != null`
- if index positive, wrote in data the event "Accuracy Test is running", `circleIndex != -1`
But this solution have a problem, we have a data line like:
![image](https://user-images.githubusercontent.com/23256059/70427155-8352ed80-1a74-11ea-9f52-ffec81fdd921.png)
_(circle name null, positions null, event name "Accuracy Test is running")_

**Comment by bastianilso** [comment]
@YoNeXia Thanks for finding this bug, and your solutions sounds good to me 🏖 - it is okay if there is a row with NaN values in it - I presume it is because the logger is capturing in-between two circles (going from BottomRight and to MiddleLeft).

**Comment by YoNeXia** [comment]
@bastianilso 
I try my solution but the circle index not change at the end of the test. So I am trying to find an other way to check when the test ended.

**Comment by bastianilso** [comment]
@YoNeXia does it not make sense to reset the CircleIndex at the end back to -1 like in beginning? Or is some code run whenever the circleindex is -1?

**Comment by YoNeXia** [comment]
@bastianilso 
I am analyzing the code to know how circleIndex works 😉
