### ISSUE TITLE
Update README.md with new visuals/text

### ISSUE THREAD

**Issue by bastianilso** [med-material/VREyeTrackingAccuracyTest#24]
In preparation for the VR Workshop, it would be great with an update to the text/pictures of VR Eye tracking accuracy test in its current state in the README.md file. It should mainly cover:
- The motivation behind the accuracy test project. 
- The intended use cases and audience.
- Bullet points with key features (pupil labs integration, assess accuracy across 9 different parts of the visual field in HMD, visualization of the gaze paths)
- Description of the connection to the R shiny application with a link to its git repository.
- A technical section on the data collection / what data is collected / explanation of what the columns means (which we already have).

**Comment by YoNeXia** [comment]
This issue was resolved with #27.
So, I close it.

![README Preview](https://user-images.githubusercontent.com/23256059/70417944-9b217600-1a62-11ea-8f41-8f391ad24ab4.png)
