### ISSUE TITLE
MainMenu Config Scene Improvements

### ISSUE THREAD

**Issue by bastianilso** [med-material/VREyeTrackingAccuracyTest#5]
The Main Menu could use a revamp. Currently it allows for input which our database doesn't understand, and it also doesn't make much effort to explain what this VR Eye Tracking Accuracy Test is about. Let's try to get closer to what's on the mockup below:

![accuracy-test-main-menu](https://user-images.githubusercontent.com/3967945/61294785-e3e84200-a7d6-11e9-9a6e-477f33f8ca5b.png)

The resources used to produce this mockup is available in the attached ZIP file.
[vr-eye-tracking-mockup-ressources.zip](https://github.com/med-material/VREyeTrackingAccuracyTest/files/3397063/vr-eye-tracking-mockup-ressources.zip)

- [x] Add instructions to the left-side, explaining what the VR Eye Tracking Accuracy Test is about.
- [x] Move the main UI to the right, above the Start Button.
- [x] Hide the current TextFields, and show "Edit" on hover, to unhide them. See [Whack-A-Mole Issue 6](https://github.com/med-material/Whack_A_Mole_VR/issues/6) for an example of what I mean.
- [x] Change the input method of putting in milliseconds, to a dropdown with four options (Switch target after 1 sec, 2 sec, or after spacebar)
- [x] Add instructions, e.g. before eye-tracking calibration "Please do not move the headset in the remaining time of the test."

**Comment by YoNeXia** [comment]
This issue was solved in pull request #10 . 🐭
