### ISSUE TITLE
Main Menu: Show Instructions to VR Participants

### ISSUE THREAD

**Issue by bastianilso** [med-material/VREyeTrackingAccuracyTest#7]
Currently the person in VR doesn't really much relevant information when the test starts. Let's add the information that we also show to the facilitator and instruct the VR participant to wait. If necessary, the resources to do this can be downloaded from issue #5.

![accuracy-test-menu-vr](https://user-images.githubusercontent.com/3967945/61295974-7853a400-a7d9-11e9-9899-c987e4832701.png)

If this ends up being too unclear in VR, we may consider to show this information as a "carousel", show each information, piece by piece and have the warning message below constantly.

**Comment by YoNeXia** [comment]
Hey @bastianilso !
I need you to test the screen in VR headset to know if you are satisfy by the new UI implemented, or if I need to make some adjustement. ☺️

**Comment by bastianilso** [comment]
When testing this, we found that there was too much content on the screen, and the important part (the warning) was pushed into blurry parts of the VR visual field. Below is a simplified (distilled) version.

![accuracy-test-menu-vr_ver2](https://user-images.githubusercontent.com/3967945/68278706-35f8f000-0072-11ea-853f-23110bd843bb.png)

**Comment by YoNeXia** [comment]
I made changements of the participant screen. Now, he match with your new mockup. I need to test it and need you to test it. Picture where I compare the mockup with the new screen.

![MockupVSScreen](https://user-images.githubusercontent.com/23256059/68593705-57087900-0496-11ea-9008-4e85802423dc.png)

_(I send you a mail when is ok, because Quentin is trying something with the VR headset)._

**Comment by YoNeXia** [comment]
I finished modifications and I tested it, its fine for me.
I think we can check new implementation afternoon, during the meeting 👍.

**Comment by YoNeXia** [comment]
This issue was resolved in pull request #21 . 🐭
