### ISSUE TITLE
R Shiny: Initial User interface with Results

### ISSUE THREAD

**Issue by bastianilso** [med-material/VREyeTrackingAccuracyTest#9]
[The R Shiny interface](http://create-rapps01.srv.aau.dk/eye-tracking/) for the VR Accuracy Eye tracking should mimic the visualization used in the VREyeTracking Application. Later we should add additional ways to analyze this data.

If you don't have access to the database yet, please have a look at the attached CSV file instead.
[eye_tracking.zip](https://github.com/med-material/VREyeTrackingAccuracyTest/files/3625600/eye_tracking.zip)

![accuracy-test-r-shiny](https://user-images.githubusercontent.com/3967945/61302004-5a8c3c00-a7e5-11e9-8b47-606502f52699.png)

- [x] Implement a dropdown where we can choose what Target (CircleName) to see. If "All Targets" are chosen, show all 9 circles next to each other. If just 1 circle is chosen (UpperLeft for example), then we should show just that 1 circle.
- [x] Implement a dropdown for Participants, where we can choose either all Participants or a specific Participant ID. When all Participants are chosen, show each participant's accuracy using a semi-transparent circle - this will create this onion-layer effect.
- [x] Implement a check list with the available conditions (non-case sensitive).
- [x] Implement a circular visualization which shows 1) the median accuracy from the available pool of participants and 2) each participant's accuracy (with semi-transparent overlaid circles on top). Color the circular visualization based on whether the median is high, low or medium.

**Comment by bastianilso** [comment]
For an example of an R shiny application (in this case for La Baguette), see here: [r-shiny-analysis-example.zip](https://github.com/med-material/VREyeTrackingAccuracyTest/files/3683069/r-shiny-analysis-example.zip)

**Comment by YoNeXia** [comment]
To show the first version of this Shiny App, go to : https://github.com/YoNeXia/VREyeTrackingAccuracyShinyApp/pull/6

In this version, circles are not exactly sames. I have not implemented the degraded of circles.

Here, you have a screen of current UI:
![Screen_Shiny_App](https://user-images.githubusercontent.com/23256059/71929820-bdf69580-319a-11ea-8119-d04962e019c2.png)
